### ISSUE TITLE
Problem running the simulator

### ISSUE THREAD

**Issue by allamiro** [fcremo/tomasulo-simulator#1]
`Traceback (most recent call last):
  File ".\simulation.py", line 5, in <module>
    import IPython
  File "C:\Users\Ta\AppData\Local\Programs\Python\Python38-32\lib\site-packages\IPython\__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "C:\Users\T\AppData\Local\Programs\Python\Python38-32\lib\site-packages\IPython\terminal\embed.py", line 17, in <module>
    from IPython.terminal.ipapp import load_default_config
  File "C:\Users\T\AppData\Local\Programs\Python\Python38-32\lib\site-packages\IPython\terminal\ipapp.py", line 28, in <module>
    from IPython.core.magics import (
  File "C:\Users\Tn\AppData\Local\Programs\Python\Python38-32\lib\site-packages\IPython\core\magics\__init__.py", line 21, in <module>
    from .execution import ExecutionMagics
  File "C:\Users\Tn\AppData\Local\Programs\Python\Python38-32\lib\site-packages\IPython\core\magics\execution.py", line 45, in <module>
    from IPython.utils.timing import clock, clock2
  File "C:\Users\Ta\AppData\Local\Programs\Python\Python38-32\lib\site-packages\IPython\utils\timing.py", line 62, in <module>
    clocku = clocks = clock = time.clock
AttributeError: module 'time' has no attribute 'clock'`

This is because he function time.clock() has been removed, after having been deprecated since Python 3.3: 
use time.perf_counter() or time.process_time()

**Comment by fcremo** [comment]
Hey there!
It's been a while since I last worked on this code, and I currently don't have time to support it.
This seems an easy fix however, so if you have time to make a PR I would gladly merge it.
Thanks for trying out this project :)
